### ISSUE TITLE
Not Responsive

### ISSUE THREAD

**Issue by PullJosh** [ScratchAgarioBots/scratchagariobots.github.io#2]
Shamefully unresponsive... but is it really a necessary fix? Mobile users aren't exactly the target audience. Let me know what you guys think.

**Comment by an-OK-squirrel** [comment]
You're on mobile? _cringes_

**Comment by PullJosh** [comment]
I'm not. I'm just asking if it's necessary to support mobile users. (I think not, but others might think otherwise.)

**Comment by an-OK-squirrel** [comment]
Whoops, I thought this was the actual bot. _hides face in shame_

**Comment by matthewr6** [comment]
Not mobile.

**Comment by PullJosh** [comment]
Okay.
